# Generated by Django 3.2 on 2021-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Название')),
                ('ShowName', models.CharField(max_length=250, verbose_name='Название для показа')),
                ('Type', models.IntegerField(verbose_name='Тип')),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Удаленность')),
                ('Descripion', models.TextField(verbose_name='Описание')),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('Photos', models.TextField(verbose_name='Фотографии')),
                ('DateDelete', models.DateField(verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Тракт',
                'verbose_name_plural': 'Тракты',
            },
        ),
    ]
