# Generated by Django 3.2 on 2021-05-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='Descripion',
            new_name='Description',
        ),
    ]
