# Generated by Django 3.2 on 2021-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20210616_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='type',
            field=models.IntegerField(choices=[(1, 'Населенный пункт'), (2, 'Садоводство'), (3, 'Коттеджный поселок'), (4, 'Местность'), (5, 'Тракт')], verbose_name='Тип'),
        ),
    ]
