# Generated by Django 3.2 on 2021-06-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_alter_locality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child', to='roads.locality'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='roads.locality'),
        ),
    ]
