# Generated by Django 3.2 on 2021-06-16 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 3, 48, 2, 565719), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_marked_receiver',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отметки получателем'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_marked_sender',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отметки отправителем'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sended',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
