# Generated by Django 3.2 on 2021-06-17 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210617_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 39, 57, 793166), verbose_name='Дата'),
        ),
    ]
