# Generated by Django 3.2 on 2021-06-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 18, 0, 35, 54, 761519), verbose_name='Дата'),
        ),
    ]
