# Generated by Django 3.2 on 2021-06-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email_phone', models.CharField(max_length=250, verbose_name='Телефон/email')),
                ('date', models.DateField(verbose_name='Дата добавления')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('for_sale', models.BooleanField(blank=True, null=True, verbose_name='На продажу')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Объект')),
                ('date_marked', models.DateField(blank=True, null=True, verbose_name='Дата отметки важного')),
                ('date_checked', models.DateField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
