# Generated by Django 3.2 on 2021-06-17 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_auto_20210617_0327'),
        ('users', '0006_alter_person_photo'),
        ('objects', '0003_auto_20210616_2148'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 6, 17, 21, 39, 26, 420255), verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_comm', to='users.person')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emp_comm', to='users.person')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='object_comm', to='objects.object')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_comm', to='requests.request')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
