# Generated by Django 3.2 on 2021-06-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 18, 0, 35, 54, 756666), verbose_name='Дата'),
        ),
    ]
