# Generated by Django 3.2 on 2021-06-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 23, 29, 48, 644583), verbose_name='Дата'),
        ),
    ]
