# Generated by Django 3.2.4 on 2021-06-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
