# Generated by Django 3.2.4 on 2021-06-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_emp_id_person_emp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
