# Generated by Django 3.2.4 on 2021-06-02 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_emp_id_person_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('type', models.IntegerField(blank=True, default=0, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(blank=True, verbose_name='Объект')),
                ('date_start', models.DateField(default=datetime.date(2021, 6, 3), verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('office_id', models.IntegerField(blank=True, verbose_name='Офис')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('for_sale', models.BooleanField(verbose_name='На продажу')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('progress', models.IntegerField(blank=True, default=0, verbose_name='Прогрес')),
                ('urgency', models.IntegerField(default=0, verbose_name='Срочность')),
                ('date_signed', models.DateField(blank=True, verbose_name='Дата подписания договора')),
                ('date_payment', models.DateField(blank=True, verbose_name='Дата оплаты')),
                ('date_frs', models.DateField(blank=True, verbose_name='Дата сдачи документов в ФРС')),
                ('date_payment_us', models.DateField(blank=True, verbose_name='Дата оплаты "ЗемляИрк"')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Покупатель', to='users.person')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Продавец', to='users.person')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
