# Generated by Django 3.2 on 2021-06-05 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20210603_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='test',
            field=models.CharField(choices=[(1, 'Обычная'), (2, 'Срочная')], default=1, max_length=250, verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 5), verbose_name='Дата начала'),
        ),
    ]
