# Generated by Django 3.2 on 2021-06-05 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20210605_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_frs',
            field=models.DateField(default=datetime.date(2021, 6, 5), null=True, verbose_name='Дата сдачи документов в ФРС'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_payment',
            field=models.DateField(default=datetime.date(2021, 6, 5), null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_payment_us',
            field=models.DateField(default=datetime.date(2021, 6, 5), null=True, verbose_name='Дата оплаты "ЗемляИрк"'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_signed',
            field=models.DateField(default=datetime.date(2021, 6, 5), null=True, verbose_name='Дата подписания договора'),
        ),
        migrations.AlterField(
            model_name='request',
            name='office_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='request',
            name='test',
            field=models.CharField(choices=[(1, 'Обычная'), (2, 'Срочная')], default=1, max_length=250, null=True, verbose_name='Test'),
        ),
    ]
