# Generated by Django 3.2 on 2021-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20210605_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='test',
            field=models.IntegerField(choices=[('1', 'Обычная'), ('2', 'Срочная')], default=1, max_length=250, null=True, verbose_name='Test'),
        ),
    ]
