# Generated by Django 3.2 on 2021-06-06 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_request_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='test',
        ),
        migrations.AlterField(
            model_name='request',
            name='date_frs',
            field=models.DateField(null=True, verbose_name='Дата сдачи документов в ФРС'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_payment',
            field=models.DateField(null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_payment_us',
            field=models.DateField(null=True, verbose_name='Дата оплаты "ЗемляИрк"'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_signed',
            field=models.DateField(null=True, verbose_name='Дата подписания договора'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 6), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='request',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Заявка оформлена'), (20, 'Ведется подбор объектов'), (40, 'Согласование с клиентом'), (60, 'Согласование с продавцом'), (80, 'Оформление документов'), (100, 'Заявка завершена')], default=1, verbose_name='Прогрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активна'), (2, 'Приостановлена'), (3, 'Завершена')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.IntegerField(choices=[(1, 'Замельный участок'), (2, 'Дача'), (3, 'Коттедж'), (4, 'Дом'), (5, 'Бизнес-объект'), (6, 'Таунхауз')], default=1, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Обычная'), (2, 'Срочная')], default=1, verbose_name='Срочность'),
        ),
    ]
