# Generated by Django 3.2 on 2021-06-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_auto_20210606_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='progress',
            field=models.IntegerField(choices=[(10, 'Заявка оформлена'), (20, 'Ведется подбор объектов'), (40, 'Согласование с клиентом'), (60, 'Согласование с продавцом'), (80, 'Оформление документов'), (100, 'Заявка завершена')], default=1, verbose_name='Прогрес'),
        ),
    ]
