# Generated by Django 3.2 on 2021-06-06 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_person_options'),
        ('requests', '0012_auto_20210606_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(default=datetime.date(2021, 6, 6), verbose_name='Дата добавления')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer', to='users.person')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request', to='requests.request')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
