# Generated by Django 3.2 on 2021-06-08 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_rename_memebers_request_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='test',
            field=models.JSONField(null=True, verbose_name='TEST'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_add',
            field=models.DateField(default=datetime.date(2021, 6, 8), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 8), verbose_name='Дата начала'),
        ),
    ]
