# Generated by Django 3.2 on 2021-06-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_person_options'),
        ('requests', '0017_auto_20210610_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='office_id',
        ),
        migrations.AddField(
            model_name='request',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office', to='users.person'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boss', to='users.person')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to='users.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
