# Generated by Django 3.2 on 2021-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_auto_20210611_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='progress',
            field=models.IntegerField(choices=[(10, 'Заявка оформлена'), (20, 'Ведется подбор объектов'), (40, 'Согласование с клиентом'), (60, 'Согласование с продавцом'), (80, 'Оформление документов'), (100, 'Заявка завершена')], default=10, verbose_name='Прогресс'),
        ),
    ]
