# Generated by Django 3.2 on 2021-06-16 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_auto_20210613_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_add',
            field=models.DateField(default=datetime.date(2021, 6, 16), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 16), verbose_name='Дата начала'),
        ),
    ]
