# Generated by Django 3.2 on 2021-06-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_auto_20210617_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_add',
            field=models.DateField(default=datetime.date(2021, 6, 18), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 18), verbose_name='Дата начала'),
        ),
    ]
