# Generated by Django 3.2 on 2021-06-19 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20210616_2148'),
        ('users', '0006_alter_person_photo'),
        ('requests', '0025_auto_20210618_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='object_id',
        ),
        migrations.AddField(
            model_name='request',
            name='object',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='objects.object'),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_add',
            field=models.DateField(default=datetime.date(2021, 6, 19), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='users.person'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 19), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='request',
            name='office',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office', to='requests.office'),
        ),
        migrations.AlterField(
            model_name='request',
            name='seller',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='users.person'),
        ),
    ]
