# Generated by Django 3.2 on 2021-06-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_person_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Земельный участок'), (2, 'Бизнес-объект'), (3, 'Дом'), (4, 'Дача'), (5, 'Коттедж'), (6, 'Готовый бизнес'), (7, 'Промышленная база'), (8, 'Таунхауз')], verbose_name='Тип объекта')),
                ('locality_id', models.IntegerField(verbose_name='Направление')),
                ('parent_id', models.IntegerField(verbose_name='Предок')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Удаленность')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь')),
                ('object_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь объекта')),
                ('other_objects', models.IntegerField(blank=True, choices=[(1, 'Дом'), (2, 'Гараж'), (3, 'Теплица'), (4, 'Баня'), (5, 'Колодец')], null=True, verbose_name='Другие объекты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_update', models.DateField(verbose_name='Дата обновления')),
                ('cadast_num', models.CharField(max_length=20, verbose_name='')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('status', models.IntegerField(choices=[(1, 'Показывается'), (2, 'Скрыт'), (3, 'Продан')], verbose_name='Статус')),
                ('posession', models.IntegerField(choices=[(1, 'Собственность'), (2, 'Не собственность'), (3, 'Садоводческая книжка'), (4, 'Аренда'), (5, 'Пожизненно наследуемое владение'), (6, 'Членская книжка')], default=1, verbose_name='Владение')),
                ('purpose', models.IntegerField(choices=[(1, 'Для индивидуального жилищного строительства'), (2, 'Для организации садоводства и жилищного строительства'), (3, 'Для ведения личного подсобного хозяйства'), (4, 'Земли водного и лесного фонда'), (5, 'Земли особо охраняемых территорий'), (6, 'Земли промышленности, транспорта, энергетики'), (7, 'Для ведения крестьянско-фермерского хозяйства'), (8, 'Для организации садоводства и дачного строительства')], default=1, verbose_name='Назначение')),
                ('source', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ресурс')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка на обзор')),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Стоимость')),
                ('comission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Комиссия')),
                ('price_conditions', models.TextField(blank=True, null=True, verbose_name='Условия цены')),
                ('good_price', models.BooleanField(verbose_name='Хорошая цена')),
                ('bargain', models.BooleanField(verbose_name='Торг')),
                ('invest_attract', models.BooleanField(verbose_name='Инвестиционная привлекательность')),
                ('photos', models.JSONField(blank=True, default='{}', null=True, verbose_name='Фотографии')),
                ('charact', models.JSONField(blank=True, default='{}', null=True, verbose_name='Харктеристики')),
                ('infrast', models.JSONField(blank=True, default='{}', null=True, verbose_name='Инфраструктура')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='Дата удалениия')),
                ('resp_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resp_emp', to='users.person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='users.person')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-date_update'],
            },
        ),
    ]
