# Generated by Django 3.2 on 2021-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='cadast_num',
            field=models.CharField(max_length=20, verbose_name='Кадастровый номер'),
        ),
    ]
