# Generated by Django 3.2 on 2021-06-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_auto_20210616_2148'),
        ('objects', '0002_alter_object_cadast_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='locality_id',
        ),
        migrations.RemoveField(
            model_name='object',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='object',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locality', to='roads.locality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='roads.locality'),
            preserve_default=False,
        ),
    ]
